### ISSUE TITLE
Short documentation on how to implement

### ISSUE THREAD

**Issue by padmalcom** [ChrisChalms/DialogueSystem#1]
Hi Chris, thanks for your framework, it looks really good! Currently I'm trying to integrate it into my game but I'm struggling with starting a dialog. Maybe you can add some bullet points to your readme on how to start a dialog in c#? That would be awesome! Regards, Jonas

**Comment by ChrisChalms** [comment]
Hi Padmalcom,

Sorry for the late response, I've only just seen your issue. First off, thanks for your interest! 

Starting a dialogue through code is definitely possible, I'll take a look at the code shortly and make it a nicer proccess and document it for you.

Thanks,
Chris

**Comment by ChrisChalms** [comment]
I've made the loading and starting of conversations from scripts a little nicer and documented it at the top of the README. Let me know if you have any more problems/requests
